### ISSUE TITLE
batch_size and other storage filtering questions

### ISSUE THREAD

**Issue by Loonride** [sjyk/deeplens-cv#9]
It looks like with the recent API changes the `put` and `get` operations of managers are supposed to work like this:

```python
def filter(header_data):
    return True
args = {'encoding': XVID, 'sample': 1.0, 'offset': 0, 'limit': 1000, 'batch_size': 10}
manager = SimpleStorageManager('test_store')
manager.put('test.mp4', 'test1', args)
res = manager.get('test1', filter, {'batch_size': 1000})
```

1. Why does `manager.get` need `batch_size`? It appears currently like it is just grabbing the number of frames specified there from the start of the video, so if you specify `{'batch_size': 5}` you would get at most 5 frames, regardless of how many frames are actually stored. This does not seem intuitive or useful, but maybe I am missing why it is actually needed.

I think it would be ideal to specify everything using the filter condition function that is passed into `get`, so if you want frames around numbers 100 to 200 you would say:

```python
def filter(header_data):
    if (header_data['start'] >= 100 and header_data['end'] <= 200):
        return True
    return False
```

2. Is this the ultimate goal of passing in condition filters, that you can specify exactly what you need, then the manager will ideally only read the storage files that match those conditions?
 
3. If so, should this filtering function also be able to grab only part of frames, such as the top 100x100 pixels? Or will it grab the whole frame, then deal with getting only a certain region? My guess is that this has to do with what type of header you are working with in the filter function.

**Comment by swjz** [comment]
1. We have two separate `StorageManager`, Simple and Full. Simple does require `batch_size`, or `clip_size` in `get()`. But Simple is just a non-optimized baseline that we use to compare to. (@j2zhao if you could elaborate a little bit more about how the `clip_size` is used here?)

You can specify a filter function using `Condition` class and `custom_filter` parameter in Full ([example](https://github.com/sjyk/deeplens-cv/blob/4b8f7df0db07e0d2c749fde4b7e8836952bbc3e1/experiments/exp1_traffic_camera.py#L69)), or using a lambda function in Simple ([example](https://github.com/sjyk/deeplens-cv/blob/4b8f7df0db07e0d2c749fde4b7e8836952bbc3e1/experiments/exp1_traffic_camera.py#L49)).

2. Yes. See the Full example above.

3. Yes, in Full you can pass a `crop` parameter to the Condition class in order to filter by a bounding box. ([code](https://github.com/sjyk/deeplens-cv/blob/4b8f7df0db07e0d2c749fde4b7e8836952bbc3e1/deeplens/full_manager/condition.py#L45) and [example](https://github.com/sjyk/deeplens-cv/blob/4b8f7df0db07e0d2c749fde4b7e8836952bbc3e1/test_get.py#L9))
